# syntax=docker/dockerfile:1

ARG UBUNTU_VERSION=20.04

FROM ubuntu:${UBUNTU_VERSION} as base


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y curl

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git

RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN python3 -m pip --no-cache-dir install --upgrade \
    setuptools

# Some TF tools expect a "python" binary
RUN ln -s $(which python3) /usr/local/bin/python

WORKDIR /app


COPY requirements.txt requirements.txt

RUN python3 -m pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["/bin/sh"]